- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Install docker-ce
  yum:
    name: docker-ce
    state: present

- name: Creates directory
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: "'http_proxy' in ansible_env or 'https_proxy' in ansible_env"

- name: Creates directory docker daemon
  file: 
    path: /etc/docker 
    state: directory
  when: "'http_proxy' in ansible_env or 'https_proxy' in ansible_env"

- template:
    src: templates/http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: '0600'
  when: "'http_proxy' in ansible_env or 'https_proxy' in ansible_env"

- name: Start service docker, if not started
  systemd:
    name: docker
    state: restarted    
    enabled: yes
    daemon_reload: yes